apiVersion: v1
kind: Service
metadata:
  name: music-app-service # Servis adınız
spec:
  type: NodePort # Minikube'de dışarıdan erişim için NodePort veya LoadBalancer
  selector:
    app: simple-app # Hangi pod'lara yönlendirme yapılacağını belirtir (deployment'daki etiketle eşleşmeli)
  ports:
  - protocol: TCP
    port: 8081       # Servis'in dinleyeceği port
    targetPort: 8081 # Container'ın (uygulamanın) dinlediği port
    # NodePort tipi kullanılıyorsa, Minikube'ün hangi porttan dışarı açacağını belirtir (opsiyonel, belirtmezseniz rastgele atanır)
    # nodePort: 30007